<?php

namespace App\Controller\Back;

use App\Entity\Mission;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class MissionCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Mission::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
//        return parent::configureCrud($crud); // TODO: Change the autogenerated stub
        return $crud
            ->setEntityLabelInSingular('Mission')
            ->setEntityLabelInPlural('Missions')
            ->setAutofocusSearch()
            ->setSearchFields(['title', 'description', 'mission.consultants.firstname', 'mission.consultants.lastname'])
            ->setDefaultSort(['end_date' => 'DESC'])
            ->setPaginatorPageSize(10)
            ->setPaginatorRangeSize(0)

            ->overrideTemplate('crud/index', 'back/mission/index.html.twig')
            ->setPageTitle('index', 'Liste des %entity_label_plural%')
            ->overrideTemplate('crud/new', 'back/mission/new.html.twig')
            ->setPageTitle('new', 'Créer une %entity_label_singular%')
            ->overrideTemplate('crud/edit', 'back/mission/edit.html.twig')
            ->setPageTitle('edit', 'Modifier une %entity_label_singular%')
            ->overrideTemplate('crud/detail', 'back/mission/detail.html.twig')
            ->setPageTitle('detail', 'Détails de la %entity_label_singular%')
            ;
    }

    /*
    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id'),
            TextField::new('title'),
            TextEditorField::new('description'),
        ];
    }
    */
}
